def get_definition():
    return {
        "name": "ExtractCoincidentPulseFeatures",
        "displayName": "Coincident Processing",
        "category": "FeatureExtraction",
        "color": [0.87, 0.47, 0.0],
        "inputs": [
            {"name": "dataIn", "type": "numeric", "required": True,
             "description": "Multizone capture (columns = zones): measurement + optional start/end indicators"},
            {"name": "trendline", "type": "numeric", "required": False,
             "description": "Baseline trend from BaselineCorrection"},
            {"name": "pulseLabels", "type": "numeric", "required": True,
             "description": "Nx2 coincident region indices (from Detection Review 'coincident')"},
            {"name": "TPsettings", "type": "struct", "required": True,
             "description": "Template settings for the measurement zone"},
            {"name": "pulseFeatures", "type": "struct", "required": False,
             "description": "Segment definitions from Template Slicing"},
            {"name": "settingsFile", "type": "string", "required": False,
             "description": "Path to saved review settings JSON"},
        ],
        "outputs": [
            {"name": "pulsePeakLocations", "type": "any",
             "description": "Peak indices per recovered particle (list of arrays)"},
            {"name": "rectangularizedPulses", "type": "any",
             "description": "Rectangularized span per recovered particle"},
            {"name": "acceptanceID", "type": "any",
             "description": "Boolean acceptance array over recovered particles"},
            {"name": "pulseStartIndices", "type": "numeric",
             "description": "Start index of each recovered particle"},
            {"name": "pulseFeatures", "type": "struct",
             "description": "Segment definitions (passed through, enriched with methods)"},
            {"name": "coincidenceMap", "type": "any",
             "description": "Per recovered particle: source event index + N"},
        ],
        "isInteractive": True,
        "runner": "runExtractCoincidentPulseFeatures",
    }
