def get_definition():
    return {
        "name": "MLSplit",
        "displayName": "ML Split",
        "category": "Sorting",
        "color": [0.6, 0.48, 0.73],
        "showPortLabels": True,
        "inputs": [
            {"name": "dataIn", "type": "struct", "required": True,
             "description": "Load File struct of labeled recordings."},
        ],
        "outputs": [
            {"name": "trainSet", "type": "struct",
             "description": "Training files as a {fileNames, files} struct."},
            {"name": "valSet", "type": "struct",
             "description": "Validation files struct."},
            {"name": "testSet", "type": "struct",
             "description": "Held-out test files struct."},
            {"name": "splitInfo", "type": "struct",
             "description": "Per-file assignment + event counts."},
        ],
        "defaultParameters": {
            "splitMode": "by file",
            "trainFrac": 0.6,
            "valFrac": 0.2,
            "testFrac": 0.2,
            "seed": 0,
        },
        "parameterDefinitions": [
            {"name": "splitMode", "displayName": "Split mode",
             "type": "choice", "options": ["by file", "by event"]},
            {"name": "trainFrac", "displayName": "Train fraction",
             "type": "numeric"},
            {"name": "valFrac", "displayName": "Val fraction",
             "type": "numeric"},
            {"name": "testFrac", "displayName": "Test fraction",
             "type": "numeric"},
            {"name": "seed", "displayName": "Seed", "type": "numeric"},
        ],
        "runner": "runMLSplit",
    }
